//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int BidID { get; set; }
        public int ItemID { get; set; }
        public int BidderID { get; set; }
        public System.DateTime BidDateTime { get; set; }
        public double BidPrice { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Member Member { get; set; }
    }
}
