//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public int ItemTypeID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public int SellerID { get; set; }
        public double MinimumBidIncrement { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public double CurrentPrice { get; set; }
    
        public virtual ItemType ItemType { get; set; }
    }
}
